export const data = [
  {
    id: 1,
    title: "Honorable",
    name: "Keelia",
    category: "Elevator",
    author: "Dyan",
    bio: "Strain of muscle, fascia and tendon of triceps, unspecified arm, sequela",
    description: "Explosion on board unspecified watercraft",
  },
  {
    id: 2,
    title: "Dr",
    name: "Sayre",
    category: "Masonry & Precast",
    author: "Clerissa",
    bio: "Open bite of left great toe without damage to nail, sequela",
    description:
      "Subluxation of metatarsophalangeal joint of unspecified toe(s), sequela",
  },
  {
    id: 3,
    title: "Dr",
    name: "Nicko",
    category: "Masonry & Precast",
    author: "Inger",
    bio: "Stress fracture, right ulna, subsequent encounter for fracture with malunion",
    description:
      "Sprain of tarsometatarsal ligament of left foot, subsequent encounter",
  },
  {
    id: 4,
    title: "Dr",
    name: "Silvan",
    category: "Casework",
    author: "Katuscha",
    bio: "Puncture wound with foreign body of right great toe with damage to nail, sequela",
    description: "Chronic osteomyelitis with draining sinus, unspecified femur",
  },
  {
    id: 5,
    title: "Mrs",
    name: "Sterne",
    category: "Granite Surfaces",
    author: "Neille",
    bio: "Acute and subacute allergic otitis media (mucoid) (sanguinous) (serous), unspecified ear",
    description:
      "Continuing pregnancy after spontaneous abortion of one fetus or more, unspecified trimester, fetus 1",
  },
  {
    id: 6,
    title: "Mr",
    name: "Nancie",
    category: "Retaining Wall and Brick Pavers",
    author: "Zeke",
    bio: "Injury of ulnar nerve at wrist and hand level of left arm, initial encounter",
    description:
      "Unspecified fracture of upper end of left radius, subsequent encounter for open fracture type IIIA, IIIB, or IIIC with malunion",
  },
  {
    id: 7,
    title: "Mr",
    name: "Coral",
    category: "HVAC",
    author: "Janot",
    bio: "Displaced fracture of capitate [os magnum] bone, unspecified wrist, subsequent encounter for fracture with nonunion",
    description: "Pelvic varices",
  },
  {
    id: 8,
    title: "Rev",
    name: "Jaquith",
    category: "Plumbing & Medical Gas",
    author: "Pavel",
    bio: "Underdosing of opium, initial encounter",
    description: "Gestational edema, first trimester",
  },
  {
    id: 9,
    title: "Mr",
    name: "Myrtle",
    category: "Fire Sprinkler System",
    author: "Chaddie",
    bio: "Anterior cord syndrome at unspecified level of cervical spinal cord",
    description: "Congenital metatarsus (primus) varus",
  },
  {
    id: 10,
    title: "Honorable",
    name: "Yardley",
    category: "Ornamental Railings",
    author: "Janetta",
    bio: "Other meniscus derangements, anterior horn of medial meniscus, left knee",
    description: "Poisoning by unspecified topical agent, assault, sequela",
  },
  {
    id: 11,
    title: "Rev",
    name: "Marsh",
    category: "Painting & Vinyl Wall Covering",
    author: "Griffy",
    bio: "Diabetes mellitus due to underlying condition with severe nonproliferative diabetic retinopathy with macular edema, unspecified eye",
    description: "Major laceration of right innominate or subclavian artery",
  },
  {
    id: 12,
    title: "Rev",
    name: "Brina",
    category: "Epoxy Flooring",
    author: "Symon",
    bio: "Generalized abdominal rigidity",
    description: "Embolism and thrombosis of thoracic aorta",
  },
  {
    id: 13,
    title: "Mrs",
    name: "Thatch",
    category: "Fire Protection",
    author: "Bartie",
    bio: "Macrocheilia",
    description:
      "Abnormal level of enzymes in specimens from female genital organs",
  },
  {
    id: 14,
    title: "Mrs",
    name: "Ilsa",
    category: "Casework",
    author: "Dita",
    bio: "Nondisplaced longitudinal fracture of unspecified patella, subsequent encounter for closed fracture with malunion",
    description: "Congenital vesico-uretero-renal reflux",
  },
  {
    id: 15,
    title: "Honorable",
    name: "Keen",
    category: "Temp Fencing, Decorative Fencing and Gates",
    author: "Roselin",
    bio: "Epidermal cyst",
    description:
      "Burn of cornea and conjunctival sac, right eye, initial encounter",
  },
  {
    id: 16,
    title: "Honorable",
    name: "Thor",
    category: "Prefabricated Aluminum Metal Canopies",
    author: "Kayne",
    bio: "Osseous obstruction of Eustachian tube, bilateral",
    description:
      "Nondisplaced fracture of head of unspecified radius, subsequent encounter for open fracture type I or II with nonunion",
  },
  {
    id: 17,
    title: "Mr",
    name: "Benedict",
    category: "Casework",
    author: "Nancee",
    bio: "Infection of amniotic sac and membranes",
    description: "Burn of third degree of unspecified knee",
  },
  {
    id: 18,
    title: "Mr",
    name: "Robbin",
    category: "Roofing (Metal)",
    author: "Sylvester",
    bio: "Injury of deep peroneal nerve at ankle and foot level, right leg",
    description:
      "Salter-Harris Type II physeal fracture of lower end of left femur, subsequent encounter for fracture with routine healing",
  },
  {
    id: 19,
    title: "Dr",
    name: "Tedd",
    category: "Site Furnishings",
    author: "Stefania",
    bio: "Displacement of prosthetic orbit of left eye",
    description:
      "Unspecified pedal cyclist injured in collision with other nonmotor vehicle in traffic accident",
  },
  {
    id: 20,
    title: "Mrs",
    name: "Tish",
    category: "Electrical and Fire Alarm",
    author: "Collie",
    bio: "Nondisplaced spiral fracture of shaft of left fibula, initial encounter for open fracture type IIIA, IIIB, or IIIC",
    description: "Laceration of adrenal gland, initial encounter",
  },
  {
    id: 21,
    title: "Mr",
    name: "Clem",
    category: "Roofing (Metal)",
    author: "Lorrin",
    bio: "Attention-deficit hyperactivity disorder, predominantly hyperactive type",
    description:
      "Person on outside of military vehicle injured in nontraffic accident",
  },
  {
    id: 22,
    title: "Dr",
    name: "Wyatt",
    category: "Marlite Panels (FED)",
    author: "Cristabel",
    bio: "Person boarding or alighting a heavy transport vehicle injured in noncollision transport accident",
    description:
      "Surgical instruments, materials and orthopedic devices (including sutures) associated with adverse incidents",
  },
  {
    id: 23,
    title: "Honorable",
    name: "Niki",
    category: "Waterproofing & Caulking",
    author: "Huey",
    bio: "Contusion and laceration of cerebrum, unspecified, with loss of consciousness of 30 minutes or less, initial encounter",
    description:
      "Other injury of unspecified muscles, fascia and tendons at forearm level, left arm, subsequent encounter",
  },
  {
    id: 24,
    title: "Mrs",
    name: "Thom",
    category: "Structural and Misc Steel (Fabrication)",
    author: "Arlyn",
    bio: "Candidiasis of skin and nail",
    description:
      "Disorder of amniotic fluid and membranes, unspecified, second trimester, fetus 5",
  },
  {
    id: 25,
    title: "Mr",
    name: "Floris",
    category: "Electrical",
    author: "Alano",
    bio: "Unspecified fracture of lower end of left tibia, subsequent encounter for open fracture type IIIA, IIIB, or IIIC with malunion",
    description:
      "Pathological fracture in neoplastic disease, unspecified femur, initial encounter for fracture",
  },
  {
    id: 26,
    title: "Ms",
    name: "Tate",
    category: "Framing (Wood)",
    author: "Gearalt",
    bio: "Sexual dysfunction, unspecified",
    description:
      "Displaced longitudinal fracture of left patella, subsequent encounter for open fracture type I or II with malunion",
  },
  {
    id: 27,
    title: "Honorable",
    name: "Aleece",
    category: "Termite Control",
    author: "Mason",
    bio: "Other specified inflammatory spondylopathies, cervicothoracic region",
    description:
      "Complete traumatic amputation of unspecified shoulder and upper arm, level unspecified",
  },
  {
    id: 28,
    title: "Rev",
    name: "Eddie",
    category: "Roofing (Metal)",
    author: "Augusto",
    bio: "Abnormalities of breathing",
    description: "Laceration of ovary, unspecified",
  },
  {
    id: 29,
    title: "Dr",
    name: "Annabela",
    category: "Hard Tile & Stone",
    author: "Skipton",
    bio: "Trochanteric bursitis, unspecified hip",
    description:
      "Partial traumatic amputation at level between elbow and wrist, right arm, initial encounter",
  },
  {
    id: 30,
    title: "Ms",
    name: "Georgy",
    category: "Painting & Vinyl Wall Covering",
    author: "Martino",
    bio: "Mixed cellularity Hodgkin lymphoma, spleen",
    description:
      "Pedestrian injured in collision with two- or three-wheeled motor vehicle in nontraffic accident",
  },
  {
    id: 31,
    title: "Mr",
    name: "Caitrin",
    category: "Fire Protection",
    author: "Gareth",
    bio: "Displaced fracture of lateral condyle of left humerus, sequela",
    description: "Posterior subcapsular polar age-related cataract, left eye",
  },
  {
    id: 32,
    title: "Honorable",
    name: "Bayard",
    category: "Drywall & Acoustical (FED)",
    author: "Marcelle",
    bio: "Other parachutist accident",
    description:
      "Cognitive deficits following nontraumatic intracerebral hemorrhage",
  },
  {
    id: 33,
    title: "Honorable",
    name: "Kelcey",
    category: "Elevator",
    author: "Kerry",
    bio: "Unspecified physeal fracture of lower end of humerus, unspecified arm, subsequent encounter for fracture with malunion",
    description:
      "Other osteoporosis with current pathological fracture, right hand",
  },
  {
    id: 34,
    title: "Dr",
    name: "Milzie",
    category: "Exterior Signage",
    author: "Chrisse",
    bio: "Encounter for cervical smear to confirm findings of recent normal smear following initial abnormal smear",
    description: "Personal history of steroid therapy",
  },
  {
    id: 35,
    title: "Mr",
    name: "Joline",
    category: "Exterior Signage",
    author: "Ava",
    bio: "Unstable burst fracture of second thoracic vertebra, sequela",
    description:
      "Unspecified physeal fracture of lower end of radius, left arm, subsequent encounter for fracture with malunion",
  },
  {
    id: 36,
    title: "Honorable",
    name: "Emlynn",
    category: "Framing (Wood)",
    author: "Crissy",
    bio: "Displaced comminuted fracture of shaft of unspecified tibia, subsequent encounter for closed fracture with delayed healing",
    description:
      "Poisoning by unspecified psychodysleptics [hallucinogens], intentional self-harm, sequela",
  },
  {
    id: 37,
    title: "Dr",
    name: "Freeland",
    category: "Framing (Wood)",
    author: "Beniamino",
    bio: "Other injury of bronchus, unspecified, subsequent encounter",
    description:
      "Dislocation of proximal interphalangeal joint of other finger, initial encounter",
  },
  {
    id: 38,
    title: "Rev",
    name: "Dolores",
    category: "Masonry & Precast",
    author: "Tan",
    bio: "Complete traumatic amputation of unspecified shoulder and upper arm, level unspecified, sequela",
    description: "Rheumatoid arthritis without rheumatoid factor, hip",
  },
  {
    id: 39,
    title: "Mr",
    name: "Joni",
    category: "Granite Surfaces",
    author: "Skippy",
    bio: "Insect bite (nonvenomous) of right ring finger, subsequent encounter",
    description:
      "Keratopathy (bullous aphakic) following cataract surgery, unspecified eye",
  },
  {
    id: 40,
    title: "Mrs",
    name: "Michale",
    category: "Waterproofing & Caulking",
    author: "Joly",
    bio: "Other specified forms of tremor",
    description: "Hypersomnia due to other mental disorder",
  },
];

export type TBook = (typeof data)[number];
